### ISSUE TITLE
Script breaks functionality of the server

### ISSUE THREAD

**Issue by Heclalava** [Feriman22/portscan-protection#1]
So I tried this script on my VPN servers, as I sell to customers in China and I want to block probing from the great firewall. It does what it supposed to do, but it breaks functionality of one of the 2 protocols used by servers (ShadowsocksR). My servers are unable to connect to the Master server when the script is active to pull client information, so it breaks the API. The other thing is I notice, it is throwing local host (127.0.0.1) into IPSet, specifically on a port used by the other protocol (v2ray) however v2ray functionality isn't disabled. 
Suggestion, add some sort of whitelist or exclusion feature so I can add domains or IP addresses to be excluded/white listed from being banned by your script. 

The other issue is there is no addition to crontab for the script to start after a reboot.

**Comment by Feriman22** [comment]
Hi,

Thank you for your feedback!

I'll add the whitelist idea to Roadmap.

The crontab entry has been created in `/etc/cron.d/portscan-protection` file and it doesn't appear when you run `crontab -l`. Please check it.


Best Regards,
Feriman

**Comment by Heclalava** [comment]
Ok I see the crontab running. However after a reboot if I verify, then the last option is disabled and doesn't give an OK. I need to install again to get all the options to show OK. (I can't remember what the option is as I have uninstalled in order to have the one VPN protocol running).

**Comment by Feriman22** [comment]
Hi,

the second (verification related) issue probably has been fixed in 01-02-2021 version.

You can update your installed version by running "/usr/local/sbin/portscan-protection.sh -up"


Please give a feedback :)
Thanks!

**Comment by Heclalava** [comment]
@Feriman22 so I added it back to one of my servers, however when I run `/usr/local/sbin/portscan-protection.sh -up` I get the following output:

```
Author: Feriman
URL: https://github.com/Feriman22/portscan-protection
Open GitHub page to read the manual and check new releases
Version: 01-02-2021
The script is up to date.
If you found it useful, please donate via PayPal: https://paypal.me/BajzaFerenc

The script is up to date.
```
However after I reboot the server and then run `sudo ./portscan-protection.sh --verify`
I get the following output:

```
Portscan Protection

Author: Feriman
URL: https://github.com/Feriman22/portscan-protection
Open GitHub page to read the manual and check new releases
Version: 28-04-2020
New version available!
If you found it useful, please donate via PayPal: https://paypal.me/BajzaFerenc


Crontab entry found. OK.
Script found. OK.
Script is executable. OK.
ipset command found. OK.
iptables command found. OK.
iptables rules are not configured!

```

So it looks like the IPtables rules aren't being set after reboot. I need to install it again to get the IPtables rules set again. 

EDIT: OK I so I deleted the previous script, redownloaded and installed again. And looks like everything is OK on verify after a reboot. I will test on this one server and see if it breaks the one VPN protocol again and monitor ipset for blocked IPs. However I see 127.0.0.1 and the port for my other VPN protocol is still being added to the ipset list, I await your whitelisting.

**Comment by Feriman22** [comment]
Thank you for your response! I'm working on the whitelist function.

**Comment by Heclalava** [comment]
OK I have tested and it is still breaking the SSR vpn protocol. I see my own personal IP address is also being added to the blocklist with the ports used to access the protocol. As soon as I install while connected to the protocol it immediately stops working, as soon as I uninstall the protocol works again.

**Comment by Feriman22** [comment]
Can you please try these commands below to ignore IP against Portscan Protection?

```
iptables -I INPUT -s <allowed_ip> -j ACCEPT #(repeat this line as needed)
iptables -P INPUT DROP
```

Thank you!

**Comment by Feriman22** [comment]
Hi,

new release has been published. Could you please update your script and test the whitelist function?


Thank you!

**Comment by Feriman22** [comment]
Hi,

did you test the new whitelist function?

Thank you!
