### ISSUE TITLE
Blocked Ips

### ISSUE THREAD

**Issue by Havard20009** [Feriman22/portscan-protection#10]
hello
how can i check the blocked ips ?or i want remove some ips from the blocked list ?

**Comment by Feriman22** [comment]
Hi @Havard20009

Try this command to list actually blocked IPs:
`ipset list port_scanners`

And try to delete them with this command:
`ipset del port_scanners <ip_address>`

**Comment by Havard20009** [comment]
is possible block ips  permanently? i think they will remove from the list after 600 seconds ?

**Comment by Feriman22** [comment]
That's right. It will remove the IP after 600 seconds. Permanent IP banning is not yet implemented in the script.

I'm going to improve the script a lot when I have time (I don't know when).

**Comment by Havard20009** [comment]
thank you very much really apricated for your time and your job. Hop you will update it soon.
thank you bro
