### ISSUE TITLE
Bad username on Debian 10

### ISSUE THREAD

**Issue by ghost** [Feriman22/portscan-protection#2]
This script works as expected, however the cron job does not seem to be running properly as `journalctl -xb` reports a cron error:

```
Error: bad username; while reading /etc/cron.d/portscan-protection
(*system*portscan-protection) ERROR (Syntax error, this crontab file will be ignored)
```

**Comment by Feriman22** [comment]
Hi VentGrey,

Thank you, I'll check this issue.

**Comment by Huntingtor** [comment]
Same here with Ubuntu 18.04.2 - the cron user  'sleep' is invalid.

**Comment by Feriman22** [comment]
Hi,

this issue has been fixed in 01-02-2021 version.

You can update your installed version by running "/usr/local/sbin/portscan-protection.sh -up"


Please give a feedback :)
Thanks!
