### ISSUE TITLE
Iptables rules of script lock me out when using WinSCP

### ISSUE THREAD

**Issue by Huntingtor** [Feriman22/portscan-protection#3]
Server: Ubuntu 18.04.2 LTS, OS at home: Win 10 Pro

[WinSCP](https://winscp.net/eng/index.php) is a FTP client for Windows. Whenever I log in there and list a directory, all is fine. But shortly after starting a transfer, I become locked out from my server. This lock remains appearantly for hours. To access the server again, only changing my dynamic ISP IP address helps.
 
 Another thing: my dynamic ISP IP address appears from time to time in _scanned_ports_ with mail ports and my Webmin port. Seems to have no effect, its only weird.

A whitelist would be highly appreciated.

**Comment by Feriman22** [comment]
Hi,

Can you please try these commands below to ignore IP against Portscan Protection?

```
iptables -I INPUT -s <allowed_ip> -j ACCEPT #(repeat this line as needed)
iptables -P INPUT DROP
```

Thank you!

**Comment by Huntingtor** [comment]
Thanks for the hint. I've done it by modifying the following rules to prevent locking myself out, including my FTP client:

(Well, inserting code with scroll bars doesn't work for me. How did you do that? Meanwhile see attachement...)

However, this isn't a real whitelist. Seems to be, that Iptables doesn't allow multipe adress ranges in one rule, only one range per rule.
[changed-rules.txt](https://github.com/Feriman22/portscan-protection/files/5935930/changed-rules.txt)

**Comment by Feriman22** [comment]
Hi,

new release has been published. Could you please update your script and test the whitelist function?


Thank you!

**Comment by Feriman22** [comment]
Hi,

did you test the new whitelist function?

Thank you!
