### ISSUE TITLE
--cron not working as expected on CentOS 8 

### ISSUE THREAD

**Issue by ronny332** [Feriman22/portscan-protection#4]
Hi there,
very nice tool, works very great "if it is working" :+1: 

I ran into issues on CentOS 8 where "/usr/sbin" is not part of the Cron daemon path system wide.
The issue is not new to me, even on Debian or Ubuntu based systems I had the path issues multiple times in the past with different applications.

What happens, when the default installation is done and the server got rebooted:
```
/usr/local/sbin/portscan-protection.sh: line 84: ipset: command not found
/usr/local/sbin/portscan-protection.sh: line 84: ipset: command not found
/usr/local/sbin/portscan-protection.sh: line 85: ipset: command not found
/usr/local/sbin/portscan-protection.sh: line 85: ipset: command not found
/usr/local/sbin/portscan-protection.sh: line 86: iptables: command not found
/usr/local/sbin/portscan-protection.sh: line 86: iptables: command not found
/usr/local/sbin/portscan-protection.sh: line 87: iptables: command not found
/usr/local/sbin/portscan-protection.sh: line 87: iptables: command not found
/usr/local/sbin/portscan-protection.sh: line 88: iptables: command not found
/usr/local/sbin/portscan-protection.sh: line 88: iptables: command not found
/usr/local/sbin/portscan-protection.sh: line 89: iptables: command not found
/usr/local/sbin/portscan-protection.sh: line 89: iptables: command not found
```
Bypassing this issue is easy:
```
@reboot root PATH=/usr/sbin:$PATH; sleep 30 && /usr/local/sbin/portscan-protection.sh --cron
```
In my eyes, it would be great, if the path modification is done within your script, or better, if your script can search for the used applications to avoid conflicts for differences within different distributions.

**Comment by Feriman22** [comment]
Hi ronny332,

Thank you for the feedback! I'll check this issue. :)

**Comment by Feriman22** [comment]
Hi ronny332,

these issues have been fixed in 01-02-2021 version.

You can update your installed version by running `/usr/local/sbin/portscan-protection.sh -up`


Please give a feedback :)
Thanks!
