### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate.

### ISSUE THREAD

**Issue by njarun** [Feriman22/portscan-protection#5]
Uninstalled with the given command and now nothing working in my system! Need help! Ubuntu 20.04

**Comment by Feriman22** [comment]
Hi @njarun,

the uninstall function only removes the created _/etc/cron.d/portscan-protection_ file, the script itself and created iptables/ipset rules, nothing else.

Can you copy here the full error message?


Thanks!
Feriman

**Comment by njarun** [comment]
Hi @Feriman22,

I updated the systemd init when I was using the portscan script and caused this issue. Fixed it now from my end. 
Closing this open issue, as its not related to the functionality of the portscan script.

Thank you,
Arun
