### ISSUE TITLE
[Question] Help on Opening port 443, 80 and 22. Close all ports and protect from scan!

### ISSUE THREAD

**Issue by njarun** [Feriman22/portscan-protection#6]
Is it possible to open the HTTP(s) port and SSH ports while using this script and protect against from the port scans, especially from nmap scans?

**Comment by Feriman22** [comment]
Hi @njarun,

this script doesn't close any port, just watch them and blocks if someone knocking on them too quickly.

**Comment by njarun** [comment]
Okey, but how do we add exception for ports 80, 443 and 22?

**Comment by Feriman22** [comment]
Currently it's not possible. You can add IP addresses to the whitelist.

**Comment by njarun** [comment]
Ok, thanks for the clarification.
