### ISSUE TITLE
Conflict with docker iptable rules

### ISSUE THREAD

**Issue by developer191** [Feriman22/portscan-protection#7]
Since you're clearing existing iptable rules before adding your own, you'll break applications that already added those rules.
It would be more useful to **append** your own rules to the existing ruleset.
As an example of conflict, I can point to **docker**.
According to the docker site, you may need to add rules to DOCKER-USER chain.
Thank you for your time.

**Comment by Feriman22** [comment]
Hi @developer191 

the issue has been fixed. Could you please try it now?

**Comment by developer191** [comment]
@Feriman22 
I confirm that removing iptables -F solved the problem.
I actually scanned a server with NMap and there is no problem in terms of functionality and it works well.
thank you.
