### ISSUE TITLE
Github not available

### ISSUE THREAD

**Issue by t0rzz** [Feriman22/portscan-protection#8]
Hey,
nice to see a new update.
The latest 2021 version had a bug:

```
root@serv ~ # ./portscan-protection.sh

Portscan Protection

Author: Feriman
URL: https://github.com/Feriman22/portscan-protection
Open GitHub page to read the manual and check new releases
Version: 01-02-2021
New version available!
If you found it useful, please donate via PayPal: https://paypal.me/BajzaFerenc

1) Install
2) Uninstall
3) Verify
4) Update
5) Quit
Please enter your choice: 4
GitHub is not available now. Try again later.
root@serv ~ #
```

I had to manually download the file from the repo. You may want to check if the update process is working fine. I can't test it anymore as the version is up-to-date.

OS: Debian 11
CURL installed.

**Comment by Feriman22** [comment]
Hey @t0rzz 

Thank you for the bugreport so much.

I would like to mention that I cannot fix it in the previous version, and it has been fixed in the current one, so I close this issue in this case.
