### ISSUE TITLE
It doesn't start after reboot on Centos 9

### ISSUE THREAD

**Issue by ETaradayko** [Feriman22/portscan-protection#9]
Hi,

After installation this script add itself to /etc/cron.d for auto-restart after reboot. But it doesn't works after 30 seconds or 30 minutes.
Now I added this functionality to /etc/rc.d/rc.local - it works like that.
You should fix this issue I think.

**Comment by Feriman22** [comment]
Hi,

can you give us the name and version number of the operating system you are using?

**Comment by ETaradayko** [comment]
Sure.
The same as subject Centos 9. 
vmlinuz-5.14.0-274.el9.x86_64 - current kernel.

NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"

**Comment by Feriman22** [comment]
Thank you for your bugreport! The issue has been fixed in the [14-03-2023](https://github.com/Feriman22/portscan-protection/releases/tag/14-03-2023) release.
